spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

app:
  upload-path: ${APP_UPLOAD_PATH:/opt/app/storage}
  jwt-secret: ${APP_JWT_SECRET}
  recaptcha-secret-key: ${APP_RECAPTCHA_SECRET}
